name: 'Graphite CI'
description: 'Optimize CI on stacked branches.'
author: 'Graphite'

branding:
  icon: 'layers'
  color: 'gray-dark'

inputs:
  graphite_token:
    description: 'Your Graphite CI secret'
    required: true
    default: ''
  endpoint:
    description: 'Your Graphite API endpoint'
    default: 'https://api.graphite.dev'
  timeout:
    description: 'Timeout for the network request to Graphite (in seconds)'
    default: '30'

outputs: {}

runs:
  using: node20
  main: dist/index.js
